language: generic
sudo: required
services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'Webox'
  env: 'webox-env-1'
  bucket_name: 'elasticbeanstalk-eu-central-1-562669185924'
  bucket_path: 'Webox'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY